src/app/app.js
src/app/dashboardView/dashboardViewCtrl.js
src/app/models/dashboardApi.js
tools/ozpDataUtility/app.js
tools/ozpDataUtility/index.html

If the user has no dashboards, create a new one named Default and load it (grid layout)
Closes #375

fix(*): Create empty dashboard if user has none

---

src/app/models/dashboardApi.js
src/common/iwcConnectedClient/iwcConnectedClient.js

Allows applications inside of webtop to get their IWC peer url from the query parameters
Closes #388

feature(dashboardApi): Send ozpIwc.peer query parameter to iframes

---

src/OzoneConfig.js
src/app/addApplicationsModal/addApplications.js
src/app/app.js
src/app/appLauncher/appLauncher.js
src/app/appToolbar/appToolbar.js
src/app/appToolbar/appToolbar.spec.js
src/app/appToolbar/appToolbar.tpl.html
src/app/constants.js
src/app/dashboardView/dashboardViewCtrl.js
src/app/dashboardView/desktop/desktop.js
src/app/dashboardView/desktop/desktop.spec.js
src/app/dashboardView/desktop/ozpmanagedframe.js
src/app/dashboardView/grid/grid.js
src/app/models/dashboardApi.js
src/app/models/dashboardApi.spec.js
src/app/ozpToolbar/ozpToolbar.js
src/app/services/iwcInterface.js
src/index.html

Application listing data is retrieved once at startup via a single http
request directly to the REST API (not separate calls via IWC). Dashboard
data is also retrieved once at startup via the REST API. Updates are
saved asynchronously via a PUT request to the REST API.
Closes #417

chore(*): Drastically reduce network traffic

---

src/app/dashboardView/chrome/ozpchrome.tpl.html
src/app/dashboardView/desktop/ozpmanagedframe.js
tools/ozpDataUtility/index.html

Replaced all glyph icons with icon font icons. Please pull before the massive switch to svgs

fix(styling): replaced all glyphicons

---

src/app/appToolbar/appToolbar.js

Fix bug where edit dashboard link could open create dashboard modal instead of edit dashboard modal
Closes #460

fix(editDashboardModal): Fix edit dashboard link

---

src/app/appToolbar/appToolbar.js
src/app/models/dashboardApi.js

Fixes several issues in sticky states when desktop layout boards are
added or when dashboard layout types are changed. Previously, the
stickyIndexes were not being updated properly, which would result in a
loss of dashboard state.
Closes #458

fix(*): Dashboard state fix when changing layouts

---

bower.json
build.config.js
src/index.html

chore(build): Use polyfill to protect against undefined console

---

src/app/models.spec.js
src/app/services/restInterface.js

fix(restInterface): Automatically retry a failed/aborted PUT request

---

src/OzoneConfig.js
src/app/app.js
src/app/ozpToolbar/ozpToolbar.js
src/app/ozpToolbar/ozpToolbar.tpl.html
src/app/settingsModal/settingsModal.js
src/app/settingsModal/settingsModal.tpl.html

settings now has a blank model in webtop
Closes #406

fix(settingsModal2):Added settings modal to webtop

---

src/OzoneConfig.js
src/app/ozpToolbar/ozpToolbar.js
src/app/ozpToolbar/ozpToolbar.tpl.html
src/app/settingsModal/settingsModal.tpl.html

All links other than those for help and profile have been updated to
point to the correct location
Refs issue #423

fix(ozpToolbar): fix most of the dead links

---

src/app/app.js
src/app/ozpToolbar/ozpToolbar.js
src/app/ozpToolbar/ozpToolbar.tpl.html
src/app/profileModal/profileModal.js
src/app/profileModal/profileModal.tpl.html

Still contains test data, but the modal is now in place and hooked up to
the ozp toolbar
Refs issue #530

feat(profileModal): Adds a profile modal template

---

src/assets/appNotFound/index.html

Updating aesthetics and wording of App Not Found page

fix(styling): App Not Found updates #475

---

src/app/ozpToolbar/ozpToolbar.js
src/app/ozpToolbar/ozpToolbar.tpl.html
src/less/main.less

Added feedback link into the HTML, provided styling, updated
configuration calls and updated requested configuration to match Center
and HUD #520

update(GlobalToolbar): Added Feedback Link #520

---

src/app/profileModal/profileModal.tpl.html
src/less/main.less

Migrated window code to use the same elements as Center and HUD.
Updated code to separate Webtop modal overrides from Bootstrap modal styling. Updated Bootstrap repo commit.

update (styling): Updated profile window styling

---

src/app/ozpToolbar/ozpToolbar.tpl.html

Updated dev resources to update as new tab

fix(Global Toolbar): Update Dev Resources to open as new tab

---

src/app/ozpToolbar/ozpToolbar.js
src/app/ozpToolbar/ozpToolbar.tpl.html

Adds logic for the link target to open in a new window for links and in
the same window for email links

fix(ozpToolbar): Feedback modal logic

---

src/app/profileModal/profileModal.js
src/app/profileModal/profileModal.tpl.html

added name, username, email
issue-534

fix(profileModal) add real user data to the profile modal display

---

src/less/main.less

Set the profile modal’s height to match Marketplace and HUD

fix(styling): Profile Modal Height

---

src/OzoneConfig.js
src/app/helpModal/helpModal.js
src/app/helpModal/helpModal.tpl.html
src/less/main.less

fix(helpModal) Add Video and Document links to Help Model

---

src/app/appToolbar/appToolbar.tpl.html
src/less/main.less

Provides the minimize icon and maximize icon in multiple sizes as will be needed by the new app chrome icons in #577

fix(icons): Add multiple icon sizes for future app chrome needs

---

src/app/ozpToolbar/ozpToolbar.js

fix(margins): Change body margins to match current toolbar sizes

---

src/OzoneConfig.js
src/app/userInterface/ozpToolbar/ozpToolbar.controller.js
src/app/userInterface/ozpToolbar/ozpToolbar.tpl.html

feat(Menu): Add helpdesk link to dropdown menu

---

src/OzoneConfig.js
src/app/metrics.js

This will enable the webtop to being reporting metrics

Adding metrics reporting to webtop

---

src/app/userInterface/helpModal/helpModal.tpl.html
src/sass/main.scss

Clean up styling, layout, and language to maintain consistency on the Help Modal across the platform.

Help modal styling

---

src/app/userInterface/addApplicationsModal/addApplicationsModal.tpl.html
src/app/userInterface/createDashboardModal/createDashboardModal.tpl.html
src/app/userInterface/settingsModal/settingsModal.tpl.html
src/sass/main.scss

This branch is parallel with the `white-modals` branch on ozp-bootstrap-sass. Waiting to push that until approved in HUD/Webtop.
New icon `icon-stack-blueDark` is now in ozp-icons to support this PR.

Light-themed bootstrap modals

---

src/sass/main.scss

fix(main.scss)bottom of app is cut off

---

src/OzoneConfig.js
src/app/userInterface/profileModal/profileModal.controller.js
src/app/userInterface/profileModal/profileModal.tpl.html

fix(profileModel)put real data in modal for new backend #534

---

src/app/userInterface/ozpToolbar/ozpToolbar.controller.js
src/app/userInterface/ozpToolbar/ozpToolbar.tpl.html

fix(Notification)not being displayed#668

---

src/app/userInterface/ozpToolbar/ozpToolbar.controller.js

Notification shows blur icon with zero messages

fix(Notification)not being displayed from center to webtop#675
